# Generated by Django 5.2.2 on 2025-06-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='current_bid',
        ),
    ]
